# 网站的标题，显示在标签栏
site: One Navigation

# 主页标题
home:
  logo:
    enable:
    type:
    text:
  title:
    text: OneNavigation
    colors:
      # 0xFF+R+G+B
      - 0xFFE91E63
      - 0xFF673AB7
  subtitle:
    text: Just One Navigation
    colors:

# 页脚
footer: Copyright © 2023 One Navigation
# Copyright © 2023 XXXXX

# 卡片图片
image:
  type: local
# 类型 local / network
# image:
#   type: network
#   text: https://...
#
# image:
#   type: local
#
# 使用local请替换 resource/card.png

# 导航地址
links:
  - name: Github
    link: https://github.com/CCZU-OSSA/OneNavigation
# links:
#   - name: 名称
#     type: FILL #TODO
#     link: https://...
