# 网站的标题，显示在标签栏
site: One Navigation

build:
  # 如果你的网站是 https://127.0.0.1/SomeString/ 而不是 https://127.0.0.1
  # 请更改此项配置为/SomeString/ ，否则留空
  base-href: /OneNavigation/
  google-proxy:
    # 代理 www.gstatic.com
    www: www.gstatic.cn
    # 代理 fonts.gstatic.com
    fonts: gstatic.loli.net

# 主题
theme:
  darkcolor: 0xFFE91E63
  lightcolor: 0xFFE91E63

# 主页标题
home:
  logo: false
  title:
    text: OneNavigation
    colors:
      # 0xFF+R+G+B
      - 0xFFE91E63
      - 0xFF673AB7
  subtitle:
    text: Just One Navigation
    colors:

# 页脚
footer: Copyright © 2023 One Navigation
# Copyright © 2023 XXXXX

# 导航地址
navigation:
  - group: OpenSource
    links:
      - name: Github
        link: https://github.com/CCZU-OSSA/OneNavigation
        tooltip: MIT LICENSE
# navigation:
#   - group: 组名
#     links:
#       - name: 名称
#         link: 链接
#         type: 按钮样式(elevated, filled, filled_tonal, outline, text, 默认为elevated)
#         tooltip: 悬浮提示
#
#
#
