# 网站的标题，显示在标签栏
site: One Navigation

theme:
  darkcolor: 0xFFE91E63
  lightcolor: 0xFFE91E63

# 主页标题
home:
  logo: false
  title:
    text: OneNavigation
    colors:
      # 0xFF+R+G+B
      - 0xFFE91E63
      - 0xFF673AB7
  subtitle:
    text: Just One Navigation
    colors:

# 页脚
footer: Copyright © 2023 One Navigation
# Copyright © 2023 XXXXX

# 导航地址
navigation:
  - group: OpenSource
    links:
      - name: Github
        link: https://github.com/CCZU-OSSA/OneNavigation