name: Page Service

on:
  push:
    branches:
      - main # default branch
  workflow_dispatch:
    
jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Build
        run: python build.py
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
